name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby-version:
          - head
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - jruby
          - jruby-head
          - truffleruby
          - truffleruby-head
          - truffleruby+graalvm
        include:
          - os: windows-latest
            ruby-version: head
          - os: windows-latest
            ruby-version: '3.4'
          - os: windows-latest
            ruby-version: mingw
          - os: windows-latest
            ruby-version: mswin
          - os: windows-latest
            ruby-version: ucrt
          - os: macos-latest
            ruby-version: 'head'
          - os: macos-latest
            ruby-version: '3.4'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # 'bundle install' and cache
    - name: Run tests
      run: bundle exec rake test
